### ISSUE TITLE
Feature Suggestion: Cyborg Mobs

### ISSUE THREAD

**Issue by K4N0** [TehStoneMan/ZombieBrains#1]
This Reminds me of an Idea i had. If you ever Watched the Terminator movies. Also Laser Creeper Mod.

Well, The Idea was to make a version of all minecraft mobs but as Futuristic and cyborg type. Also they drop technology that can be refined by some method and can be used to create a Hacking PDA or tool of sort. Then the Mobs can be Hacked and can be turned to help you. Also they are healed / Repaired by feeding them rotten flesh. Even Passive Mobs look cyborg but can't be hacked. A Config for changing their health would be great.
Love the idea of this mod thou.

**Comment by TehStoneMan** [comment]
Sound like an interesting idea, but I don't think cybe-rmobs would fit within the concept of this mod.

**Comment by K4N0** [comment]
Okay. just a thought.
